### ISSUE TITLE
有没有一种可能，微信读书的客户端提供了自动阅读的功能，不需要这个插件

### ISSUE THREAD

**Issue by frankthinker** [DoooReyn/WxRead-WebAutoReader#17]
当你在iOS设备，Android设备或者其他移动端设备上运行相应平台的微信读书App时，进入浏览书本内容的界面：

    当你点击右上角三个点的按钮时，会弹出菜单选项，你会看见其中一个选项是“自动阅读”

所以目前根本用不到这个插件。
你想刷时长用移动端就行了，不会有人没手机吧？

**Comment by DoooReyn** [comment]
初衷是在 PC 上使用。
