### ISSUE TITLE
看完一本书后再次点击书签没有反应

### ISSUE THREAD

**Issue by Lovely-Wildpointer** [DoooReyn/WxRead-WebAutoReader#2]
删除书签后新建一个一样的仍然无法使用

**Comment by DoooReyn** [comment]
尝试刷新页面再点击

**Comment by DoooReyn** [comment]
> 删除书签后新建一个一样的仍然无法使用

尝试刷新页面再点击

**Comment by Lovely-Wildpointer** [comment]
> > 删除书签后新建一个一样的仍然无法使用
> 
> 尝试刷新页面再点击

刷新过了，没用，但是点击第二章就可以使用。
《肖申克的救赎》这本书点击开始阅读就没有反应，作者可以试试。其他的都还好，还是感谢您的项目。

**Comment by DoooReyn** [comment]
> > > 删除书签后新建一个一样的仍然无法使用
> > 
> > 
> > 尝试刷新页面再点击
> 
> 刷新过了，没用，但是点击第二章就可以使用。
> 《肖申克的救赎》这本书点击开始阅读就没有反应，作者可以试试。其他的都还好，还是感谢您的项目。

问题描述： **在书本首页使用无效**
问题原因：首页获取书本标题和章节名称失败，目前采用默认名称代替
问题解决：[查看commit](https://github.com/DoooReyn/WxRead-WebAutoReader/commit/6583e83659608b7d689d41112e3030d185cd80f6)

请更新后重新尝试。
