### ISSUE TITLE
能否增加mac的客户端

### ISSUE THREAD

**Issue by ojeo** [DoooReyn/WxRead-WebAutoReader#8]
能否增加mac的客户端？
代码我clone后在mac下无法执行

**Comment by DoooReyn** [comment]
Mac借出去了，等拿回时找时间添上，请耐心等待回复。

**Comment by DoooReyn** [comment]
或者你可以移步[PC版](https://github.com/DoooReyn/WxRead-PC-AutoReader)，加一份Mac的配置进行打包。 @ojeo
