### ISSUE TITLE
刷了两天没有增加时长

### ISSUE THREAD

**Issue by fyzzy1943** [DoooReyn/WxRead-WebAutoReader#9]
使用的 chrome，网页版微信阅读。可以确认开始刷了，网页标题显示进度，书本自动滚动和翻章节。使用书籍：鹿鼎记。

刷了几小时之后，发现阅读时间还是手机打开看的2分钟。

是不是网页版的不算时长啦，还是加了检测啥的。

**Comment by DoooReyn** [comment]
建议先使用PC版。网页端限制比较多，功能也有限，因此有段时间没维护了，后续有空了我会跟进的。

**Comment by fyzzy1943** [comment]
又刷了几次，发现有时候是可以的，有时候不行；而且在读书小队和阅读时长里，这俩时间有时候也不统一。
感觉时长没加不是脚本的问题；
今天出现了一个新的问题：鹿鼎记有50多章，今天读到47章的时候，提示我读完了。。不过这都是小问题。

**Comment by DoooReyn** [comment]
> 又刷了几次，发现有时候是可以的，有时候不行；而且在读书小队和阅读时长里，这俩时间有时候也不统一。
> 感觉时长没加不是脚本的问题；
> 今天出现了一个新的问题：鹿鼎记有50多章，今天读到47章的时候，提示我读完了。。不过这都是小问题。

- PC版的时长基本是稳定的，还是建议使用PC版。
- 读完的判定是找不到下一章按钮了，有时候因为网络加载慢了，下一章按钮没有加载出来，因此判定为已读完。

**Comment by fyzzy1943** [comment]
主要还是现在没pc，现在读书小队里显示30多个小时，列表里的阅读时长是10多个小时，不过都小事，读书小队里有效就行了

**Comment by DoooReyn** [comment]
> 主要还是现在没pc，现在读书小队里显示30多个小时，列表里的阅读时长是10多个小时，不过都小事，读书小队里有效就行了

有读书小队推荐吗？😊

**Comment by fyzzy1943** [comment]
> > 主要还是现在没pc，现在读书小队里显示30多个小时，列表里的阅读时长是10多个小时，不过都小事，读书小队里有效就行了
> 
> 有读书小队推荐吗？😊

求带呀
